### ISSUE TITLE
Adding new weapons to the game

### ISSUE THREAD

**Issue by JEmanuel1806** [red-eclipse/world#47] opened 2018-03-07 19:17 UTC
I know a similar question has been asked before, but not quite the one that i have. My question is, how is it possible  to add weapons for the game (offline mode only)? I guess you have to work on the src and compile it, but my question would be if anyone may could help me out on which one(s) i have to edit and how. 
For example how could i copy a weapon to be in the game twice with different parameters (faster speed, damage, sound etc.) , for example 2x smg , but with different attributes. 
As is said it is not for online mode, just for offline only. Any Help oder Hints appreciated, thank you.

**Comment by SniperGoth** [comment] 2018-03-07 19:33
Adding weapons itself would be through the source code i believe, but you can also replace the existing models with some tweaking around. then make variables for themselves, even if that's not exactly what you asked for.

**Comment by JEmanuel1806** [comment] 2018-03-07 19:38
Thanks for the answer. Yes i know , already did these too. But i wanted to see if anybody had any idea how to add some. My guess was to edit one of the Weapon code files, but i am still figuring out which one. Even if its just a copy of an already existing model, does not matter (could replace design, sounds etc.  afterwards).

**Comment by JeffBobbo** [comment] 2018-03-07 21:00
In [game/weapdef.h](https://github.com/red-eclipse/base/blob/master/src/game/weapdef.h) file, basically every time you see a reference to the weapons, you'd need to add a new reference for your new weapon. e.g., add w13 to line 2, move line 12 `GVAR(flags, grenade##name, mn, w09, mx); \` down a line, change w09 to w10 etc for the following entries, add `GVAR(flags, yourweap#name, nm, w09, mx); \` to line 12 (which should be blank)*.
You then need to set the stats in [game/weapons.h](https://github.com/red-eclipse/base/blob/master/src/game/weapons.h).

Unfortunately, the git repository doesn't go far enough back to find when the zapper was introduced, and I'm not certain if it was in an older git repository before a reworking or in the old SVN. There may be more you need to do, but I don't know all the details.

If you made such a modification, do not go online with it compiled in. Can almost guarantee bad stuff will happen.

* If you do this, I'd find it highly likely that weapon spawners on maps would break; as they're ID based you may find grenade spawners instead spawn your new weapon, mine spawners spawn grenades and the rocket spawner spawns mines. You could, of course, fix that by easily by making your new weapon `w13`, but that means it'll come after rocket in the weapon list when you've got both of them.

**Comment by JEmanuel1806** [comment] 2018-03-07 21:11
thank you very much, I'll try my best. But really appreciate your help. 
And no its really just for offline (since it would not be any use in MP anyways)

**Comment by qreeves** [comment] 2018-03-08 04:41
We're a game, not an engine/API, so we don't really provide documentation on how to use the code. It is assumed you have at least some level of competency with C++, so I'd recommend starting with something simple before moving on to something as difficult as modding a game.

That being said, you can pretty much make your own weapon by changing the variables for a particular weapon. Every weapon works according to the rules in [weapons.h](https://github.com/red-eclipse/base/blob/master/src/game/weapons.h) so you can do almost anything to change their behaviour (and usually, if someone wants a new option, I'm open to adding it even if we aren't really going to use it ourselves).

There's a few (unofficial) things out there demonstrating this:
* http://www.instructables.com/id/Red-Eclipse-Weaponry-Development/
* https://www.youtube.com/watch?v=1E3_c_kL14E
* https://www.youtube.com/watch?v=_ixq4bWySvU

**Comment by Goldenbrain1** [comment] 2018-03-08 13:48
Is it possible to do similar modifications on the server and that the players connected will be able to use them ?

**Comment by qreeves** [comment] 2018-03-08 14:18
With variables, yes. With code, not really.

**Comment by Goldenbrain1** [comment] 2018-03-09 09:33
I mean if i add a weapon on my server, will the players connected be able to use it ?
Or if i add a code that chatkill impossible (because i hate chatkill :) ), will it work for the people online ?

**Comment by SniperGoth** [comment] 2018-03-09 11:19
"I mean if i add a weapon on my server, will the players connected be able to use it ? "
No, because that's client-side only, that means that if you make a server with your own weapon added to the roster, only you will be able to use it, and that's considered cheating.

"Or if i add a code that chatkill impossible (because i hate chatkill :) ), will it work for the people online ?"
There's a high chance that it will work, and a high chance that it will get you banned, as that's considered cheating :p  (modifying the source code for benefits only you have).

**Comment by qreeves** [comment] 2018-03-09 11:44
If you add a weapon by source code there's no method of transferring that to vanilla clients that don't have your source modifications. We've created the variable system to allow the server to define how existing weapons behave, it allows you to almost completely redefine a weapon to be whatever you want it to be. This is the recommended option if you want to list your server on our master server, because otherwise your making a different game for which you'd need your own master server.

It is possible to make a modification to the server wherein which it can ignore your events for someone marked as chatting (the particulars of which are too much for a forum post), but the problem is the client does not know that person is protected and will see damage being done on their end causing a conflict of input/output. This type of modification wouldn't be allowed on our master server due to being game breaking, and again you're making your own game at that point.

That being said, I could add a server side variable to perform the suggested anti-chatkill feature in RE itself, then it's just a matter of switching the variable on for your server (we'd default it to off unless a poll is done to determine if it should be on by default).

It all really depends on what you're trying to do, customise your Red Eclipse server, or create your own game via source code edits.

**Comment by JEmanuel1806** [comment] 2018-03-10 22:37
okay so i managed to successfully add plenty of weapons to the game now (5 more to be precise) in the last few days, which worked fine, thanks to your help. Now today i added my sixth, but now i got a problem with the game. It usually crashes when loading a map (which is not empty), or when trying to load the weapon. The error contains the message "Code 11: Segmentation Error".

According as i remember it this indicates either a memory problem of the computer , a bug in the code (really hope it is) or an exceess of given memory.

So i wanted to ask if there is a limit of weapons that can be added?
Or at least a safespace that can be exceeded. (or fix)
Since i believe the error lays somewhere in the (my) code.

Thanks

**Comment by qreeves** [comment] 2018-03-11 01:51
Search for all instances of `W_MAX` and make sure you've added the weapons to the other parts of the code as well. You also need to update `projs.cpp` etc.

**Comment by qreeves** [comment] 2018-10-05 05:34
Closing due to being marked as solved. If you still require help please feel free to open a new request.

**Closed** 2018-10-05 05:35 UTC
Labels: question, solved, support request
